### ISSUE TITLE
Implement the SpeckleDynamoConverter

### ISSUE THREAD

**Issue by teocomi** [speckleworks/SpeckleDynamo#10]
https://github.com/speckleworks/SpeckleDynamo/blob/master/SpeckleDynamoConverter/SpeckleDynamoConverter.cs

### Status
**Primitives**
- [x] Numbers
- [x] Boolean
- [x] String
- [x] Null
- [x] Point
- [x] Vector
- [x] Plane

**Linear**
- [x] Line
- [x] Polygon
- [x] Rectangle
- [x] Polyline (Dynamo PolyCurve with all its curves straigth)

**Curves**
- [x] Circle
- [x] Arc (still buggy due some differences with Rhino)
- [x] Ellipse
- [x] EllipseArc (only `ToSpeckle()` as NurbsCurve)
- [x] Curve
- [x] PolyCurve
- [x] NurbsCurve
- [x] Helix (only `ToSpeckle()` as NurbsCurve)

**Other Geometries**
- [x] Mesh
- [ ] Solids
- [ ] Brep (SpeckleBrep needs a more defined structure)
- [ ] Box (can be  converted as Cuboid?)
- [ ] Extrusion (same as Brep)

**Without Dynamo counterpart (?)**
- Interval
- Annotation
- ArchivableDictionary/ Dictionary

**Comment by alvpickmans** [comment]
I've updated @teocomi's main thread to reflect the current status of `SpeckleDynamoConverter`.

**Comment by alvpickmans** [comment]
All but brep/surface based geometries are implemented now. Closing this issue.
