### ISSUE TITLE
Add code to serialize sender and receiver upon save

### ISSUE THREAD

**Issue by teocomi** [speckleworks/SpeckleDynamo#16]
And as well to reinitialize sender and receiver when opening a saved file

**Comment by radumg** [comment]
hey @teocomi , where should we serialise/store this to ?

**Comment by teocomi** [comment]
Using the `SerializeCore` and `DeserializeCore` overrides. Look the same in Dynamo 2.0 and earlier versions...

See: https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodeModels/Input/DoubleSlider.cs#L140

**Comment by Shyroby** [comment]
hi @teocomi  i'd like to collaborate to your project.

**Comment by didimitrie** [comment]
@Shyroby best is to get on the slack and ping @teocomi (matteo) in the #speckle-dynamo channel!

**Comment by Shyroby** [comment]
Ok can u send me the right slack workspace url...i can't login.

**Comment by didimitrie** [comment]
https://slacker.speckle.works/ (linked from the website footer)
