### ISSUE TITLE
Method not found: 'Void Dynamo.Graph.Nodes.NodeModel.ClearErrorsAndWarnings()'.

### ISSUE THREAD

**Issue by vasshaug** [speckleworks/SpeckleDynamo#25]
Hey. I'm getting this after opening new graph and adding "Speckle Receiver" to canvas in Automatic mode. Same in Manual mode.

"Warning: Whilst preparing to run, this node encountered a problem. Please talk to the creators of the node, and give them this message:

Method not found: 'Void Dynamo.Graph.Nodes.NodeModel.ClearErrorsAndWarnings()'."

Win 10, Revit 2018.2, Dynamo 1.3.2, Speckle for Dynamo 0.0.2.

![revit_2018-06-22_14-22-39](https://user-images.githubusercontent.com/5300197/41776803-6b0cf950-7629-11e8-8ca6-f2319ef75164.png)

**Comment by ksobon** [comment]
@vasshaug @teocomi it looks like this version released has a dependency on Dynamo 2.0: 

![image](https://user-images.githubusercontent.com/529781/41778044-629564ca-75fb-11e8-9de5-72aec267693d.png)

Is that intentional?

**Comment by didimitrie** [comment]
afaik we decided to support dynamo 2+. so yep, update is required! we don't have bandwidth for backwards compatibility 🤖 

I'll close for now.

**Comment by teocomi** [comment]
Yup, Dynamo 2.0 only, should probably implement some version checking since the package manager isn’t preventing installation on older versions...
