### ISSUE TITLE
Add Dynamo version check on init

### ISSUE THREAD

**Issue by radumg** [speckleworks/SpeckleDynamo#26]
#### Expected Behaviour
Speckle for Dynamo should only work in Dynamo `2.0` and above, see [comment](https://github.com/speckleworks/SpeckleDynamo/issues/25#issuecomment-399544422) in #25.

#### Actual Behaviour
Happily installs on any version of Dynamo.

#### Proposed Solution (if any)
- version check on Speckle for Dynamo extension init
- warn user via a `MessageBox` or similar ?

**Comment by alvpickmans** [comment]
Good to also state it on the package description, "Built for 2.x" or similar to prevent users to install it on the first place if using 1.x

**Comment by radumg** [comment]
i'm thinking rather than a message box, we raise a warning on the Nodes themselves ?

**Comment by teocomi** [comment]
Fixed for the next release.
