### ISSUE TITLE
Empty Receiver is not saved

### ISSUE THREAD

**Issue by teocomi** [speckleworks/SpeckleDynamo#28]
Non initialized Receivers are not saved correctly and don't show up upon re-opening. Might be a speckle core issue.

![image](https://user-images.githubusercontent.com/2679513/42216135-b51629ee-7eb8-11e8-801f-506b61599dac.png)

**Comment by didimitrie** [comment]
Fastest close eveeeer!  

I get weird behaviour in grasshopper as well, but actually not critical. Empty receivers, when opening the file again, just ask for account selection again which still sucks, but not crucial...

**Comment by teocomi** [comment]
Was a silly bug on my side, not related to Core ;)

**Comment by didimitrie** [comment]
yes, well, this triggered the find of a similar issue in gh 🎊
