### ISSUE TITLE
Get User Data does not work with meshes (?)

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleDynamo#44]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

Curves seem fine;  nevertheless with a mesh with user data you get:
```
Warning: UserData.Get expects argument type(s) (Geometry), but was called with (Autodesk.DesignScript.Geometry.Mesh)
```
🙃

**Comment by teocomi** [comment]
Fixed it in dev, will push soon. @alvpickmans there doesn't seem to be a way to cast a mesh as geometry, right?

**Comment by alvpickmans** [comment]
Don't remember if geometries and meshes are both inheriting from DesignScriptEntity or not
