### ISSUE TITLE
Closed Polyline interpreted as "open" polyline

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleDynamo#48]
Step 0: 
- [ ] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
How things should actually work!

closed polyline > closed polyline

#### Actual Behaviour
What's actually going on!
![polycurveissue](https://user-images.githubusercontent.com/22736626/48067077-9f2ff400-e1cf-11e8-84b6-14833f62d31b.PNG)

Hi, I've tested for the first time SpeckleDynamo, I've sent a closed polyline from Grasshopper to Dynamo, it works but restults as an open polyline

#### Affected Projects
Does this issue propagate to other dependencies or dependants? If so, list them here!

**Comment by alvpickmans** [comment]
I'll have a look now, is it the latest version?

**Comment by PaulPoinet** [comment]
yes I just installed Revit 2019 and Dynamo 2.0.1, and pulled Speckle from the Package manager

**Comment by alvpickmans** [comment]
That should do it. I'll merge to dev and you can give it a go. 👍

**Comment by alvpickmans** [comment]
@PaulPoinet you can try to install it from the latest build https://ci.appveyor.com/api/buildjobs/uw70w2waoeh91qr0/artifacts/SpeckleDynamo-0.0.5.106.zip

**Comment by alvpickmans** [comment]
@PaulPoinet you can try to install it from the latest build https://ci.appveyor.com/api/buildjobs/uw70w2waoeh91qr0/artifacts/SpeckleDynamo-0.0.5.106.zip

**Comment by PaulPoinet** [comment]
@teocomi @alvpickmans ok! sorry I thought that when you merge changes it builds the app automatically as it is done for grasshopper. thanks!
