### ISSUE TITLE
User data set to a mesh does not get streamed

### ISSUE THREAD

**Issue by ggooskens** [speckleworks/SpeckleDynamo#54]
See images. Sending meshes with user data from GH works as expected.

![61ad0d0c](https://user-images.githubusercontent.com/36707790/50907673-41ff2b80-1428-11e9-8503-474e96dd0550.PNG)
![2f28719d](https://user-images.githubusercontent.com/36707790/50907674-41ff2b80-1428-11e9-97e6-a702d1276da5.PNG)

**Comment by alvpickmans** [comment]
@ggooskens there was a minor error on the converter that was preventing from attaching properties, now fixed.
Still upon receiving meshes, properties show as null. Might be something during serialisation/deserialisation @didimitrie @teocomi any thoughts?
I cannot test it on GH at the moment but can issue happens on Dynamo as well.

**Comment by teocomi** [comment]
🚀 @alvpickmans !
Will investigate in the next days!

**Comment by didimitrie** [comment]
uhh i guess this comment is more relevant here: https://github.com/speckleworks/SpeckleDynamo/issues/55#issuecomment-456386486
