### ISSUE TITLE
String properties in dictionaries do not work

### ISSUE THREAD

**Issue by fernandoruizz** [speckleworks/SpeckleDynamo#57]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

Attached a dyn file showing strings properties in dictionaries are causing an error on the Speckle plugin.
[Extract&link.zip](https://github.com/speckleworks/SpeckleDynamo/files/2865699/Extract.link.zip)

Numbers and Yes/No parameters work fine.

**Comment by didimitrie** [comment]
Hello @fernandoruizz! Actually they do! Some of the parameter values were not strings and causing errors 😎 

Adding a `String from Object` node in between parameter value and the dictionary by keys node sorted everything out:

![image](https://user-images.githubusercontent.com/7696515/53096723-afb67100-3517-11e9-9d45-43721d6f53ef.png)

🍸
