### ISSUE TITLE
First sender on the canvas refreshes its streamid on file reopen

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleDynamo#61]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

This a nasty issue. If you place a dynamo sender on the canvas, on reopening the file, it will refresh its stream id (which is not the intended behaviour). 

The crazy part is that this happens only **to the first sender node**; any other subsequent sender nodes placed on the canvas are behaving as expected - no streamId refresh. 

Reproduced in dynamo sandbox.

**Comment by didimitrie** [comment]
Extra info: this happens only if you close dynamo completely, not just the defintion file.

**Comment by teocomi** [comment]
fixed in b25c0e4f2bc9da32ea528a4c62fe82ec1e63a1fe
