### ISSUE TITLE
Add SpeckleDynamo for Civil 3D installation path to installer

### ISSUE THREAD

**Issue by Jeast85** [speckleworks/SpeckleDynamo#65]
Step 0: 
- [x ] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
How things should actually work!

Now with the release of Dynamo for Civil3D/AutoCAD 2020, please add the following path to the installer:
C:\Users\%USERNAME%\AppData\Roaming\Autodesk\C3D 2020\Dynamo\2.1\packages

**Comment by teocomi** [comment]
Hey @Jeast85, happy to do that once we release Speckle for Dynamo 2.1!

**Comment by teocomi** [comment]
Added (long ago actually 😓)
