### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleDynamo#8]
Update the README with:
- [x] Image / Screenshot of Dynamo Add-In
- [x] Build Instructions
- [x] Usage Instructions

**Comment by teocomi** [comment]
Will do. Is it fine to keep readme and the wip code in the 'dev' branch until we have a first release?

**Comment by didimitrie** [comment]
maybe we can have a notice in the master/readme.md re dev branch being where stuff goes down until that amazing release moment...
